language: julia
os:
  - linux
  - osx
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
cache:
 directories:
   - /home/travis/.julia
sudo: false
addons:
  apt_packages:
    - gfortran
    - liblapack-dev
    - libgmp-dev
    - libglpk-dev

before_install:
    # don't keep an old version of the code in the cache
  - julia -e 'if "PowerModelsAnnex" in keys(Pkg.installed()) Pkg.rm("PowerModelsAnnex"); Pkg.rm("PowerModelsAnnex") end'
  - julia -e 'Pkg.update()' #make sure we get the latest version of METADATA
  - julia -e 'if !("Coverage" in keys(Pkg.installed())) Pkg.add("Coverage") end'
  #- julia -e 'if !("Documenter" in keys(Pkg.installed())) Pkg.add("Documenter") end'

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd())'
  - julia -e 'Pkg.test("PowerModelsAnnex", coverage=true)'

after_success:
  - export REPO_TOKEN=c36f2b09-17d0-4983-bd61-347894b7d6d6; julia -e 'using Coverage; cd(Pkg.dir("PowerModelsAnnex")); Codecov.submit(process_folder("."));'
  #- julia -e 'cd(Pkg.dir("PowerModelsAnnex")); include(joinpath("docs", "make.jl"))'
