name = "PowerModelsAnnex"
uuid = "6e471128-d39d-5672-b02b-a742bd1b77ed"
authors = ["Carleton Coffrin, et. al."]
repo = "https://github.com/lanl-ansi/PowerModelsAnnex.jl"
version = "0.9.0"

[deps]
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PowerModels = "c36e90e8-916a-50a6-bd94-075b64ef4655"

[compat]
InfrastructureModels = "~0.6, ~0.7"
Ipopt = "1"
JuMP = "1"
Memento = "~1.0, ~1.1, ~1.2, ~1.3, ~1.4"
PowerModels = "~0.20"
julia = "1.6"

[extras]
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Ipopt", "Test"]

